// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "TrialFund – Prop Trading Firm",
	description:
		"TrialFund is a next-generation prop trading firm providing traders with funded accounts, flexible rules, and instant access to capital.",
	keywords: [
		"TrialFund",
		"prop firm",
		"funded trading account",
		"forex trading",
		"prop trading challenge",
		"instant funding",
	],
	authors: [{ name: "TrialFund" }],
	creator: "TrialFund",
	publisher: "TrialFund",
	openGraph: {
		title: "TrialFund – Prop Trading Firm",
		description:
			"Trade with confidence. TrialFund gives traders access to capital, risk management, and growth opportunities.",
		url: "https://trialfund.com",
		siteName: "TrialFund",
		images: [
			{
				url: "https://trialfund.com/og-image.png", // replace with your real image path
				width: 1200,
				height: 630,
				alt: "TrialFund Prop Firm",
			},
		],
		locale: "en_US",
		type: "website",
	},
	twitter: {
		card: "summary_large_image",
		title: "TrialFund – Prop Trading Firm",
		description:
			"Get funded and scale your trading career with TrialFund. Trade smarter, not harder.",
		images: ["https://trialfund.com/og-image.png"], // replace with your real image path
		creator: "@trialfund", // replace with your Twitter handle
	},
	icons: {
		icon: "/favicon.ico",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
